{
 "title": "Cloudio",
 "description": "Dein IoT Office Buddy",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cloudio_temp" }
   ]
  },
  {
   "title": "Luftqualität",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "cloudio_luftqualitaet" }
   ]
  },
  {
   "title": "Luftfeuchte",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "cloudio_luftfeuchte" }
   ]
  },
  {
   "title": "über Zeit",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cloudio_temp" },
    { "expr": "cloudio_luftfeuchte" },
    { "expr": "cloudio_luftqualitaet" }
   ]
  }
 ]
}